Develop3
vovaserbqa/QA-java-diplom-3 pull request #1
Opened 2023-11-15 20:13 UTC by vovaserbqa

added task number 3

2023-11-17 13:23 UTC, pavel-ulan requested changes
Тут конечно похуже. И проверки забыл сделать, и драйвер неверно подкидываешь, да и структура местами хромает.

2023-11-17 13:23 UTC, pavel-ulan commented on src/test/java/AuthTest.java
> +        System.setProperty("webdriver.chrome.driver", "C:\\chromedriver-win32\\chromedriver.exe");
**надо исправить**
плохо. такой подход не оставляет вариантов запуска без предварительного исправления (в том числе запуска в рамках CI pipeline). Помимо этого необходимо подключить 2 браузера Google Chrome и Яндекс.Браузер.
Как правило, если есть какие-то кейсовые ситуации и файл надо иметь в доступе, то его помещают в property папку и указывают к нему относительный путь. Тогда и файл хранится вместе с кодом и работает на любой системе не завися от пути (т.к. путь относительный от src/). Сразу скажу, что для драйверов это не прокатит. Используй тут драйвер менеджер (ну и реализуй какой-то параметр для выбора нужного браузера. например по проверке Enum поля с названием браузера)

2023-11-17 13:23 UTC, pavel-ulan commented on src/test/java/AuthTest.java
> +        System.setProperty("webdriver.chrome.driver", "C:\\chromedriver-win32\\chromedriver.exe");
ну и сам сетап драйвера я бы посоветовал вынести в родительский класс. зачем делать это в каждом Before методе каждого тестового класса, если можно инициализацию вынести в родительский Before и просто наследовать тестовые классы.

2023-11-17 13:23 UTC, pavel-ulan commented on src/test/java/AuthTest.java
> +        .loginIn(email, password);
**надо исправить**
ты создаешь registerPage в Before, а MainPage и AuthPage в тесте, почему?
по хорошему, инициализации страниц в теле теста быть не должно. 
Первое - они будут создаваться (объекты страниц) при каждом запуске теста, хотя нам ничего не мешает использовать один объект на все тесты, т.к. это PO и он не меняется. Так что POты лучше вообще инжектить. Но можно инициализировать в Before или в виде поля класса хотя бы.
Второе и главное - где проверка? В loginIn ее тоже нет =). Assert обязателен. Любой тест это проверка чего-то. Исправь пожалуйста

2023-11-17 13:23 UTC, pavel-ulan commented on src/test/java/AuthTest.java
> +        authPage.login(email, password);
аналогично

2023-11-17 13:23 UTC, pavel-ulan commented on src/test/java/ConstructorTest.java
> +        assertThat(constructorPage.bunsSection(), CoreMatchers.containsString("tab_tab_type_current"));
**можно лучше**
я бы сказал, что containsString("tab_tab_type_current") не очень красиво выглядит в теле теста. А использование строкового значения без обертки (хоть константой сделай что ли), это вообще плохая практика. Значительно лучше было бы просто сделать локатор который подсвечивает активный элемент и проверять, активен ли текущий элемент.

2023-11-17 13:23 UTC, pavel-ulan commented on src/test/java/ProfileTest.java
> +        personalAreaPage.waitForExitButton();
ну, я надеюсь ты догадываешься чего тут не хватает =)

2023-11-17 13:23 UTC, pavel-ulan commented on src/main/java/pageobject/AuthPage.java
> +        return this;
**надо исправить**
навесь аннотацию Step на все методы-шаги которые используешь. Это позволяет лучше понимать код, правильно читается Allure и в целом показывает что ты хорошо знаком с правилами репорт-фреймворка.

2023-11-17 13:23 UTC, pavel-ulan commented on src/test/java/ProfileTest.java
> +        registerPage.register(name, email, password);
**надо исправить**
смотри, ты используешь медленный и нестабильный UI слой для регистрации пользователя, хотя по тесту этого не требуется. В таких ситуациях правильно использовать более стабильные и быстрые решения. Например в прошлом задании ты мог видеть АПИколл для регистрации пользователя. Это еще один слой этогоже приложения. Используй АПИ колл. Это и надежнее и правильнее с архитектурной точки зрения.

2023-11-21 14:29 UTC, pavel-ulan approved these changes
Ну, все еще есть вопросы к структуре, но уже значительно лучше, молодцом

2023-11-21 14:29 UTC, pavel-ulan commented on Diplom_Vladimir_Serbin_25_2.txt
😆  я имел в виду прикрепить его в трекере. Зачем он тут? я же как-то уже открыл твой репозиторий и задание =)

2023-11-21 14:29 UTC, pavel-ulan commented on src/main/java/model/LoginPage.java
> +        mainPage.waitForLoadElement();
**можно лучше **
что в ЛогинСтранице делают МэйнСтраница?
Это PO паттерн. тут должны быть только действия для текущей страницы. Хочешь вынести сценарий - создай доп класс

2023-11-21 14:41 UTC, vovaserbqa commented on src/main/java/model/LoginPage.java
> +        mainPage.waitForLoadElement();
Я это сделал намеренно что бы не разносить по классам логику

2023-11-21 14:41 UTC, vovaserbqa commented on src/main/java/model/LoginPage.java
> +        mainPage.waitForLoadElement();
> **можно лучше ** что в ЛогинСтранице делают МэйнСтраница? Это PO паттерн. тут должны быть только действия для текущей страницы. Хочешь вынести сценарий - создай доп класс

можно так оставить?

2023-11-21 17:06 UTC, merged